apiVersion: v2
name: kasm-web
description: "Helm chart for deploying KasmWeb Ubuntu desktop"
type: application
version: 0.1.0
appVersion: "1.15.0"
keywords:
  - kasmweb
  - ubuntu
  - desktop
  - vnc
home: https://github.com/kasmtech/kasmweb
sources:
  - https://github.com/kasmtech/kasmweb
maintainers:
  - name: Your Name
    email: your.email@example.com
    url: https://your-website.com
dependencies: []
icon: https://kasmweb.com/favicon.ico  # 可选：用于图标

