apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "my-ubuntu-desktop.fullname" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.size }}
  {{- if .Values.volume.storageClassName }}
  storageClassName: {{ .Values.volume.storageClassName }}
  {{- end }}
